# Generated by Django 4.2.2 on 2024-06-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Servicedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Service_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Service_Image', models.ImageField(blank=True, null=True, upload_to='Service Images')),
                ('Included', models.CharField(blank=True, max_length=100, null=True)),
                ('Excluded', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
