# Generated by Django 3.2.10 on 2024-06-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_add_servicedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_categorydb',
            name='Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
