# Generated by Django 3.2.10 on 2024-06-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_add_categorydb_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTypedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Service_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
