# Generated by Django 3.2.10 on 2024-06-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_servicetypedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_servicedb',
            name='Select_Service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
