# Generated by Django 3.2.10 on 2024-07-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_remove_add_servicedb_select_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_servicedb',
            name='Discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='add_servicedb',
            name='Discount_Type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
