# Generated by Django 3.2.10 on 2024-07-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20240701_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_servicedb',
            name='Discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
