# Generated by Django 3.2.10 on 2024-07-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_alter_add_servicedb_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_servicedb',
            name='Discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='add_servicedb',
            name='Discount_Type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percent')], max_length=100, null=True),
        ),
    ]
