# Generated by Django 3.2.10 on 2024-07-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_city_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
