# Generated by Django 3.2.10 on 2024-07-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_registerdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdb',
            name='Confirm_Password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
