# Generated by Django 3.2.10 on 2024-07-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_cartdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
