# Generated by Django 3.2.10 on 2024-07-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_alter_cartdb_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Total_Price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
