# Generated by Django 3.2.10 on 2024-07-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_alter_cartdb_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Total_Price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
