# Generated by Django 3.2.10 on 2024-07-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_alter_cartdb_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
