# Generated by Django 3.2.10 on 2024-07-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_auto_20240712_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
