# Generated by Django 3.2.10 on 2024-07-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0012_auto_20240714_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
