# Generated by Django 3.2.10 on 2024-07-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0013_auto_20240714_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Complaint_image', models.ImageField(blank=True, null=True, upload_to='complaint_images')),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
