# Generated by Django 3.2.10 on 2024-08-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0014_bookingdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdb',
            name='Discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='Total_Price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
