# Generated by Django 3.2.10 on 2024-08-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0015_auto_20240801_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdb',
            name='Discount',
        ),
        migrations.RemoveField(
            model_name='bookingdb',
            name='Total_Price',
        ),
    ]
