# Generated by Django 3.2.10 on 2024-08-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0016_auto_20240802_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Discount_Type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percent')], default='fixed', max_length=10),
        ),
    ]
