# Generated by Django 3.2.10 on 2024-08-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0018_bookingdb_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdb',
            name='Total_Price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
