# Generated by Django 3.2.10 on 2024-08-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0019_bookingdb_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdb',
            name='Total_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
