# Generated by Django 3.2.10 on 2024-08-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0020_alter_bookingdb_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdb',
            name='Email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookingdb',
            name='Phone',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdb',
            name='Total_Price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
