# Generated by Django 3.2.10 on 2024-08-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0021_auto_20240806_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdb',
            name='Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
